import 'package:flutter/material.dart';
import 'models.dart';

List<Category> dummyCategories = [
  Category(id: '1', title: 'Donuts', iconPath: ''),
  Category(id: '2', title: 'Burger', iconPath: ''),
  Category(id: '3', title: 'Smothie', iconPath: ''),
  Category(id: '4', title: 'PanCake', iconPath: ''),
  Category(id: '5', title: 'Pizza', iconPath: ''),
];

List<Donut> dummyProducts = [
  // --- Category 1: Donuts ---
  Donut(
    id: '1',
    categoryId: '1',
    title: 'Nuts Caramel',
    subtitle: "Dunkin's",
    price: 36.0,
    imagePath: 'assets/images/donut_blue.png',
    backgroundColor: const Color(0xFFE8F8FA),
    titleColor: const Color(0xFF1CB0E1),
    description:
        'The Sweet And Subtle Salty Combo Of Chocolate Meets Caramel. Introduce The Caramel Duo To Your Mouth!',
    ingredients: [
      Ingredient(
        name: 'Sugar',
        amount: '8 Gram',
        percentage: 2,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Salt',
        amount: '8 Gram',
        percentage: 0.3,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '8 Gram',
        percentage: 12,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '140 Kcal',
        percentage: 40,
        color: Colors.pink[100]!,
      ),
    ],
  ),
  Donut(
    id: '2',
    categoryId: '1',
    title: 'Red Velvet',
    subtitle: "Dunkin's",
    price: 45.0,
    imagePath: 'assets/images/donut_red.png',
    backgroundColor: const Color(0xFFFFF2F4),
    titleColor: const Color(0xFFFF486A),
    description:
        'A classic red velvet treat with smooth cream cheese flavor and wonderful texture.',
    ingredients: [
      Ingredient(
        name: 'Sugar',
        amount: '10 Gram',
        percentage: 3,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Salt',
        amount: '5 Gram',
        percentage: 0.2,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '8 Gram',
        percentage: 12,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '160 Kcal',
        percentage: 45,
        color: Colors.pink[100]!,
      ),
    ],
  ),
  Donut(
    id: '3',
    categoryId: '1',
    title: 'Strawberry',
    subtitle: "Dunkin's",
    price: 84.0,
    imagePath: 'assets/images/donut_strawberry.png',
    backgroundColor: const Color(0xFFFDF0F6),
    titleColor: const Color(0xFFFF69B4),
    description:
        'Sweet strawberry icing with a delightful glaze loop for the perfect bite.',
    ingredients: [
      Ingredient(
        name: 'Sugar',
        amount: '9 Gram',
        percentage: 2.5,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Salt',
        amount: '4 Gram',
        percentage: 0.2,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '7 Gram',
        percentage: 10,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '130 Kcal',
        percentage: 35,
        color: Colors.pink[100]!,
      ),
    ],
  ),
  Donut(
    id: '4',
    categoryId: '1',
    title: 'Choco Tap',
    subtitle: "Dunkin's",
    price: 95.0,
    imagePath: 'assets/images/donut_choco.png',
    backgroundColor: const Color(0xFFFFF7EF),
    titleColor: const Color(0xFFFFB067),
    description:
        'Rich chocolate dipped donut with wonderful zig-zags of golden goodness.',
    ingredients: [
      Ingredient(
        name: 'Sugar',
        amount: '12 Gram',
        percentage: 4,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Salt',
        amount: '6 Gram',
        percentage: 0.3,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '14 Gram',
        percentage: 15,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '180 Kcal',
        percentage: 50,
        color: Colors.pink[100]!,
      ),
    ],
  ),

  // --- Category 2: Burgers ---
  Donut(
    id: 'b1',
    categoryId: '2',
    title: 'Classic Burger',
    subtitle: 'Burger King',
    price: 15.0,
    imagePath: 'assets/images/burger1.jpg',
    backgroundColor: const Color(0xFFFFF7EF),
    titleColor: const Color(0xFFFFB067),
    description:
        'A classic juicy cheeseburger perfect for lunch with lettuce and a soft bun.',
    ingredients: [
      Ingredient(
        name: 'Beef',
        amount: '200g',
        percentage: 40,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Salt',
        amount: '2g',
        percentage: 0.1,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '25g',
        percentage: 20,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '450 Kcal',
        percentage: 70,
        color: Colors.pink[100]!,
      ),
    ],
  ),
  Donut(
    id: 'b2',
    categoryId: '2',
    title: 'Double Trouble',
    subtitle: 'Burger King',
    price: 22.0,
    imagePath: 'assets/images/burger2.jpg',
    backgroundColor: const Color(0xFFE8F8FA),
    titleColor: const Color(0xFF1CB0E1),
    description:
        'Double the meat, double the cheese, double the deliciousness.',
    ingredients: [
      Ingredient(
        name: 'Beef',
        amount: '400g',
        percentage: 80,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Salt',
        amount: '4g',
        percentage: 0.2,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '50g',
        percentage: 40,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '900 Kcal',
        percentage: 95,
        color: Colors.pink[100]!,
      ),
    ],
  ),
  Donut(
    id: 'b3',
    categoryId: '2',
    title: 'Chicken Delight',
    subtitle: 'KFC',
    price: 18.0,
    imagePath: 'assets/images/burger3.jpg',
    backgroundColor: const Color(0xFFFFF2F4),
    titleColor: const Color(0xFFFF486A),
    description:
        'Crispy fried chicken breast in a brioche bun with spicy mayo.',
    ingredients: [
      Ingredient(
        name: 'Chicken',
        amount: '180g',
        percentage: 35,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Salt',
        amount: '3g',
        percentage: 0.15,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '20g',
        percentage: 18,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '500 Kcal',
        percentage: 75,
        color: Colors.pink[100]!,
      ),
    ],
  ),
  Donut(
    id: 'b4',
    categoryId: '2',
    title: 'Veggie Supreme',
    subtitle: 'Healthy Bites',
    price: 16.5,
    imagePath: 'assets/images/burger4.jpg',
    backgroundColor: const Color(0xFFFDF0F6),
    titleColor: const Color(0xFFFF69B4),
    description:
        '100% plant-based patty with fresh tomatoes, onions and lettuce.',
    ingredients: [
      Ingredient(
        name: 'Veg',
        amount: '150g',
        percentage: 30,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Salt',
        amount: '1.5g',
        percentage: 0.08,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '10g',
        percentage: 10,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '350 Kcal',
        percentage: 55,
        color: Colors.pink[100]!,
      ),
    ],
  ),

  // --- Category 3: Smoothies ---
  Donut(
    id: 's1',
    categoryId: '3',
    title: 'Berry Blast',
    subtitle: 'Juice Bar',
    price: 8.5,
    imagePath: 'assets/images/smoothie1.jpg',
    backgroundColor: const Color(0xFFFDF0F6),
    titleColor: const Color(0xFFFF69B4),
    description:
        'A fresh, cold, and delicious mix of strawberries and raspberries.',
    ingredients: [
      Ingredient(
        name: 'Sugar',
        amount: '15g',
        percentage: 5,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Fruit',
        amount: '100g',
        percentage: 40,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '0g',
        percentage: 0,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '120 Kcal',
        percentage: 10,
        color: Colors.pink[100]!,
      ),
    ],
  ),
  Donut(
    id: 's2',
    categoryId: '3',
    title: 'Green Detox',
    subtitle: 'Juice Bar',
    price: 9.0,
    imagePath: 'assets/images/smoothie2.jpg',
    backgroundColor: const Color(0xFFE8F8FA),
    titleColor: const Color(0xFF1CB0E1),
    description: 'A healthy mix of spinach, kiwi, mint, and green apple.',
    ingredients: [
      Ingredient(
        name: 'Sugar',
        amount: '5g',
        percentage: 1.5,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Fruit',
        amount: '150g',
        percentage: 60,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '0g',
        percentage: 0,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '80 Kcal',
        percentage: 5,
        color: Colors.pink[100]!,
      ),
    ],
  ),
  Donut(
    id: 's3',
    categoryId: '3',
    title: 'Mango Magic',
    subtitle: 'TropiJuice',
    price: 7.5,
    imagePath: 'assets/images/smoothie3.jpg',
    backgroundColor: const Color(0xFFFFF7EF),
    titleColor: const Color(0xFFFFB067),
    description: 'Sweet and tropical mango smoothie to cool down your day.',
    ingredients: [
      Ingredient(
        name: 'Sugar',
        amount: '22g',
        percentage: 8,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Fruit',
        amount: '120g',
        percentage: 45,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '0g',
        percentage: 0,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '150 Kcal',
        percentage: 12,
        color: Colors.pink[100]!,
      ),
    ],
  ),
  Donut(
    id: 's4',
    categoryId: '3',
    title: 'Cherry Vanilla',
    subtitle: 'Juice Bar',
    price: 10.0,
    imagePath: 'assets/images/smoothie4.jpg',
    backgroundColor: const Color(0xFFFFF2F4),
    titleColor: const Color(0xFFFF486A),
    description: 'Creamy vanilla blended with ripe cherries.',
    ingredients: [
      Ingredient(
        name: 'Sugar',
        amount: '18g',
        percentage: 6,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Fruit',
        amount: '90g',
        percentage: 35,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '2g',
        percentage: 1,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '180 Kcal',
        percentage: 15,
        color: Colors.pink[100]!,
      ),
    ],
  ),

  // --- Category 4: PanCake ---
  Donut(
    id: 'p1',
    categoryId: '4',
    title: 'Syrup Stack',
    subtitle: 'IHOP',
    price: 18.0,
    imagePath: 'assets/images/pancake1.jpg',
    backgroundColor: const Color(0xFFFFF7EF),
    titleColor: const Color(0xFFFFB067),
    description:
        'A fluffy stack of pancakes topped with a square of butter and dripping syrup.',
    ingredients: [
      Ingredient(
        name: 'Sugar',
        amount: '35g',
        percentage: 15,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Carbs',
        amount: '60g',
        percentage: 30,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '12g',
        percentage: 15,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '350 Kcal',
        percentage: 40,
        color: Colors.pink[100]!,
      ),
    ],
  ),
  Donut(
    id: 'p2',
    categoryId: '4',
    title: 'Berry Pancakes',
    subtitle: 'IHOP',
    price: 20.0,
    imagePath: 'assets/images/pancake2.jpg',
    backgroundColor: const Color(0xFFFDF0F6),
    titleColor: const Color(0xFFFF69B4),
    description: 'Fresh blueberries and raspberries served over warm pancakes.',
    ingredients: [
      Ingredient(
        name: 'Sugar',
        amount: '25g',
        percentage: 10,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Carbs',
        amount: '50g',
        percentage: 25,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '10g',
        percentage: 12,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '320 Kcal',
        percentage: 35,
        color: Colors.pink[100]!,
      ),
    ],
  ),
  Donut(
    id: 'p3',
    categoryId: '4',
    title: 'Choco Bliss',
    subtitle: 'Sweet Treats',
    price: 21.0,
    imagePath: 'assets/images/pancake3.jpg',
    backgroundColor: const Color(0xFFE8F8FA),
    titleColor: const Color(0xFF1CB0E1),
    description:
        'Pancakes drizzled with rich chocolate sauce and whipped cream.',
    ingredients: [
      Ingredient(
        name: 'Sugar',
        amount: '45g',
        percentage: 20,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Carbs',
        amount: '70g',
        percentage: 35,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '18g',
        percentage: 22,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '480 Kcal',
        percentage: 55,
        color: Colors.pink[100]!,
      ),
    ],
  ),
  Donut(
    id: 'p4',
    categoryId: '4',
    title: 'Classic Stack',
    subtitle: 'Diner 66',
    price: 15.0,
    imagePath: 'assets/images/pancake4.jpg',
    backgroundColor: const Color(0xFFFFF2F4),
    titleColor: const Color(0xFFFF486A),
    description: 'Simple, traditional fluffy pancakes with a hint of vanilla.',
    ingredients: [
      Ingredient(
        name: 'Sugar',
        amount: '20g',
        percentage: 8,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Carbs',
        amount: '55g',
        percentage: 28,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '8g',
        percentage: 10,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '290 Kcal',
        percentage: 32,
        color: Colors.pink[100]!,
      ),
    ],
  ),

  // --- Category 5: Pizza ---
  Donut(
    id: 'pz1',
    categoryId: '5',
    title: 'Pepperoni Slice',
    subtitle: "Domino's",
    price: 5.0,
    imagePath: 'assets/images/pizza1.jpg',
    backgroundColor: const Color(0xFFFFF2F4),
    titleColor: const Color(0xFFFF486A),
    description:
        'A delicious triangle slice of pepperoni pizza with stringy cheese.',
    ingredients: [
      Ingredient(
        name: 'Carbs',
        amount: '40g',
        percentage: 20,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Salt',
        amount: '3g',
        percentage: 1.5,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '18g',
        percentage: 25,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '280 Kcal',
        percentage: 30,
        color: Colors.pink[100]!,
      ),
    ],
  ),
  Donut(
    id: 'pz2',
    categoryId: '5',
    title: 'Margherita',
    subtitle: "Luigi's",
    price: 24.0,
    imagePath: 'assets/images/pizza2.jpg',
    backgroundColor: const Color(0xFFFFF7EF),
    titleColor: const Color(0xFFFFB067),
    description:
        'Traditional Italian margherita with fresh basil and mozzarella.',
    ingredients: [
      Ingredient(
        name: 'Carbs',
        amount: '60g',
        percentage: 30,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Salt',
        amount: '2.5g',
        percentage: 1.2,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '14g',
        percentage: 18,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '450 Kcal',
        percentage: 50,
        color: Colors.pink[100]!,
      ),
    ],
  ),
  Donut(
    id: 'pz3',
    categoryId: '5',
    title: 'Veggie Pizza',
    subtitle: "Green Eats",
    price: 22.0,
    imagePath: 'assets/images/pizza3.jpg',
    backgroundColor: const Color(0xFFE8F8FA),
    titleColor: const Color(0xFF1CB0E1),
    description: 'Loaded with bell peppers, onions, tomatoes, and olives.',
    ingredients: [
      Ingredient(
        name: 'Carbs',
        amount: '55g',
        percentage: 28,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Salt',
        amount: '2g',
        percentage: 1.0,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '10g',
        percentage: 12,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '380 Kcal',
        percentage: 42,
        color: Colors.pink[100]!,
      ),
    ],
  ),
  Donut(
    id: 'pz4',
    categoryId: '5',
    title: 'Mushroom Truffle',
    subtitle: "Gourmet Pies",
    price: 28.0,
    imagePath: 'assets/images/pizza4.jpg',
    backgroundColor: const Color(0xFFFDF0F6),
    titleColor: const Color(0xFFFF69B4),
    description: 'Earthy mushrooms paired with rich truffle oil and parmesan.',
    ingredients: [
      Ingredient(
        name: 'Carbs',
        amount: '50g',
        percentage: 25,
        color: Colors.blue[300]!,
      ),
      Ingredient(
        name: 'Salt',
        amount: '3.5g',
        percentage: 1.8,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Fat',
        amount: '22g',
        percentage: 30,
        color: Colors.pink[100]!,
      ),
      Ingredient(
        name: 'Energy',
        amount: '520 Kcal',
        percentage: 60,
        color: Colors.pink[100]!,
      ),
    ],
  ),
];
